language: java
sudo: false
jdk: oraclejdk11
addons:
  sonarqube:
    organization: "beduino"
    branches:
     - master
script:
#    - mvn dependency:copy-dependencies
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true
    - mvn test -B
#    - mvn jacoco:report -B
    - sonar-scanner
# reference https://docs.travis-ci.com/user/sonarqube/
# reference https://docs.travis-ci.com/user/languages/java/
